config/routes.rb
Rails.application.routes.draw do
  mount ReportsKit::Engine, at: '/'

  get 'query/search' => 'query#search', :as => 'search_page'
  get 'query' => 'query#index'
  post 'query/search' => 'query#search'
  post 'query/game' => 'query#game'

  devise_for :app_users
  resources :votes
  resources :games
  resources :teams, shallow: true do
  	resources :players 
  	resources :coaches 
  	resources :owners  
  	resources :managers 
    resources :articles do
      resources :comments, only: [:create, :index, :destroy]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'teams#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 	has_many :comments, dependent: :destroy

end

app/models/article.rb
class Article < ApplicationRecord
  # self.primary_keys = :title, :team_id
  belongs_to :team
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, allow_blank: false
  validates :articletext, presence: true, allow_blank: false
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :team
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :article, :foreign_key => [:title, :team_id]
  belongs_to :article
  belongs_to :app_user


  validates :body, presence: true, allow_blank: false
end

app/models/game.rb
class Game < ApplicationRecord
	self.primary_keys = :hometeam_id, :gamedate
  belongs_to :hometeam, :class_name => 'Team'
  belongs_to :awayteam, :class_name => 'Team'
  belongs_to :winningteam, :class_name => 'Team', optional: true

end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :team
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :players, dependent: :destroy
	has_many :managers, dependent: :destroy
	has_one :owner, dependent: :destroy
	has_many :coaches, dependent: :destroy
	has_many :articles, dependent: :destroy

	has_many :hometeams, :class_name => "Game", :foreign_key => 'hometeam_id', dependent: :destroy
	has_many :awayteams, :class_name => "Game", :foreign_key => 'awayteam_id', dependent: :destroy
	has_many :winningteams, :class_name => "Game", :foreign_key => 'winningteam_id', dependent: :destroy

  validates :yearfounded, numericality: { only_integer: true, greater_than: 0, less_than: 2020 }

   def full_name
  	"#{fullname}"
  end
  
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article, :foreign_key => 'email'
  # belongs_to :user
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :only => [:new, :create, :edit, :update, :destroy] do
    if (! (current_app_user && current_app_user.admin) )
      flash[:alert] = 'Only admins can access that functionality.' 
      redirect_to(root_path)
    end
  end
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    @comments = @article.comments.all
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :articletext, :timeposted, :team_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article, url: @article.new_record? ? team_articles_path : article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :articletext %>
    <%= form.text_area :articletext %>
  </div>

  <div class="field">
    <%= form.label :timeposted %>
    <%= form.datetime_select :timeposted %>
  </div>

  <div class="select">
    <%= form.label :team_id %>
    <% form.text_field :team_id %>
    <%= form.collection_select(:team_id, Team.all, :id, :full_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article, class: 'btn btn-primary' %> 
<%= link_to 'Back', team_articles_path(@article.team), class: 'btn btn-primary' %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
      <th>Time Posted</th>
      <th>Team</th>
      <th>Links</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <% if article.team_id == params{1}["team_id"].to_i %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.articletext.truncate(20) %></td>
          <td><%= article.timeposted %></td>
          <td><%= article.team.fullname %></td>
          <td><%= link_to ("<i class='far fa-eye'></i>").html_safe, article %></td> 
          <td><%= link_to ("<i class='fas fa-edit fa-sm'></i>").html_safe, edit_article_path(article) %></td>
          <td><%= link_to ("<i class='fa fa-trash fa-sm'></i>").html_safe, article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_team_article_path, class: 'btn btn-primary' %> 
<%= link_to 'Back to Teams', teams_path, class: 'btn btn-primary' %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', team_articles_path, class: 'btn btn-primary' %>

app/views/articles/show.html.erb
<h1>
  <%= @article.title %>
</h1>

<p>
  <strong>Text:</strong>
  <%= @article.articletext %>
</p>

<p>
  <strong>Time Posted:</strong>
  <%= @article.timeposted %>
</p>

<p>
  <strong>Team:</strong>
  <%= @article.team.fullname %>
</p>

<h3>Comments</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.app_user.email %>:</strong>
    <%= comment.body %>
    <p><i><%= comment.created_at.to_time.strftime('%B %e at %l:%M %p') %></i>
      <%= link_to ("<i class='fa fa-trash fa-sm'></i>").html_safe, comment_path(comment), method: :delete, data: { confirm: 'Are you sure?' } %></p>
   
  </div>
<% end %>
<%= render partial: 'comments/form' %>
<br>  
<%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-primary' %> 
<%= link_to 'Back', team_articles_path(@article.team), class: 'btn btn-primary' %>