config/routes.rb
Rails.application.routes.draw do
  mount ReportsKit::Engine, at: '/'

  get 'query/search' => 'query#search', :as => 'search_page'
  get 'query' => 'query#index'
  post 'query/search' => 'query#search'
  post 'query/game' => 'query#game'

  devise_for :app_users
  resources :votes
  resources :games
  resources :teams, shallow: true do
  	resources :players 
  	resources :coaches 
  	resources :owners  
  	resources :managers 
    resources :articles do
      resources :comments, only: [:create, :index, :destroy]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'teams#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 	has_many :comments, dependent: :destroy

end

app/models/article.rb
class Article < ApplicationRecord
  # self.primary_keys = :title, :team_id
  belongs_to :team
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, allow_blank: false
  validates :articletext, presence: true, allow_blank: false
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :team
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :article, :foreign_key => [:title, :team_id]
  belongs_to :article
  belongs_to :app_user


  validates :body, presence: true, allow_blank: false
end

app/models/game.rb
class Game < ApplicationRecord
	self.primary_keys = :hometeam_id, :gamedate
  belongs_to :hometeam, :class_name => 'Team'
  belongs_to :awayteam, :class_name => 'Team'
  belongs_to :winningteam, :class_name => 'Team', optional: true

end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :team
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :players, dependent: :destroy
	has_many :managers, dependent: :destroy
	has_one :owner, dependent: :destroy
	has_many :coaches, dependent: :destroy
	has_many :articles, dependent: :destroy

	has_many :hometeams, :class_name => "Game", :foreign_key => 'hometeam_id', dependent: :destroy
	has_many :awayteams, :class_name => "Game", :foreign_key => 'awayteam_id', dependent: :destroy
	has_many :winningteams, :class_name => "Game", :foreign_key => 'winningteam_id', dependent: :destroy

  validates :yearfounded, numericality: { only_integer: true, greater_than: 0, less_than: 2020 }

   def full_name
  	"#{fullname}"
  end
  
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article, :foreign_key => 'email'
  # belongs_to :user
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController
  before_action :only => [:new, :create, :edit, :update, :destroy] do
    if (! (current_app_user && current_app_user.admin) )
      flash[:alert] = 'Only admins can access that functionality.' 
      redirect_to(root_path)
    end
  end
  before_action :set_manager, only: [:show, :edit, :update, :destroy]

  # GET /managers
  # GET /managers.json
  def index
    @managers = Manager.all
  end

  # GET /managers/1
  # GET /managers/1.json
  def show
  end

  # GET /managers/new
  def new
    @manager = Manager.new
  end

  # GET /managers/1/edit
  def edit
  end

  # POST /managers
  # POST /managers.json
  def create
    @manager = Manager.new(manager_params)

    respond_to do |format|
      if @manager.save
        format.html { redirect_to @manager, notice: 'Manager was successfully created.' }
        format.json { render :show, status: :created, location: @manager }
      else
        format.html { render :new }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managers/1
  # PATCH/PUT /managers/1.json
  def update
    respond_to do |format|
      if @manager.update(manager_params)
        format.html { redirect_to @manager, notice: 'Manager was successfully updated.' }
        format.json { render :show, status: :ok, location: @manager }
      else
        format.html { render :edit }
        format.json { render json: @manager.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managers/1
  # DELETE /managers/1.json
  def destroy
    @manager.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Manager was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manager
      @manager = Manager.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def manager_params
      params.require(:manager).permit(:firstname, :lastname, :team_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/managers/_form.html.erb
<%= form_with(model: @manager, url: @manager.new_record? ? team_managers_path : manager, local: true) do |form| %>
  <% if manager.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manager.errors.count, "error") %> prohibited this manager from being saved:</h2>

      <ul>
      <% manager.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="select">
    <%= form.label :team_id %>
    <% form.text_field :team_id %>
    <%= form.collection_select(:team_id, Team.all, :id, :full_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/managers/edit.html.erb
<h1>Editing Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Show', @manager, class: 'btn btn-primary' %> 
<%= link_to 'Back', team_managers_path(@manager.team), class: 'btn btn-primary' %>

app/views/managers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Managers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Team</th>
      <th>Links</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @managers.each do |manager| %>
      <% if manager.team_id == params{1}["team_id"].to_i %>
        <tr>
          <td><%= manager.firstname %></td>
          <td><%= manager.lastname %></td>
          <td><%= manager.team.fullname %></td>
          <td><%= link_to 'Show', manager %></td>
          <td><%= link_to 'Edit', edit_manager_path(manager) %></td>
          <td><%= link_to 'Destroy', manager, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manager', new_team_manager_path, class: 'btn btn-primary' %>

app/views/managers/new.html.erb
<h1>New Manager</h1>

<%= render 'form', manager: @manager %>

<%= link_to 'Back', team_managers_path, class: 'btn btn-primary' %>

app/views/managers/show.html.erb
<p>
  <strong>Firstname:</strong>
  <%= @manager.firstname %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @manager.lastname %>
</p>

<p>
  <strong>Team:</strong>
  <%= @manager.team.fullname %>
</p>

<%= link_to 'Edit', edit_manager_path(@manager), class: 'btn btn-primary' %> 
<%= link_to 'Back', team_managers_path(@manager.team), class: 'btn btn-primary' %>