config/routes.rb
Rails.application.routes.draw do
  mount ReportsKit::Engine, at: '/'

  get 'query/search' => 'query#search', :as => 'search_page'
  get 'query' => 'query#index'
  post 'query/search' => 'query#search'
  post 'query/game' => 'query#game'

  devise_for :app_users
  resources :votes
  resources :games
  resources :teams, shallow: true do
  	resources :players 
  	resources :coaches 
  	resources :owners  
  	resources :managers 
    resources :articles do
      resources :comments, only: [:create, :index, :destroy]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'teams#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 	has_many :comments, dependent: :destroy

end

app/models/article.rb
class Article < ApplicationRecord
  # self.primary_keys = :title, :team_id
  belongs_to :team
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, allow_blank: false
  validates :articletext, presence: true, allow_blank: false
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :team
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :article, :foreign_key => [:title, :team_id]
  belongs_to :article
  belongs_to :app_user


  validates :body, presence: true, allow_blank: false
end

app/models/game.rb
class Game < ApplicationRecord
	self.primary_keys = :hometeam_id, :gamedate
  belongs_to :hometeam, :class_name => 'Team'
  belongs_to :awayteam, :class_name => 'Team'
  belongs_to :winningteam, :class_name => 'Team', optional: true

end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :team
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :players, dependent: :destroy
	has_many :managers, dependent: :destroy
	has_one :owner, dependent: :destroy
	has_many :coaches, dependent: :destroy
	has_many :articles, dependent: :destroy

	has_many :hometeams, :class_name => "Game", :foreign_key => 'hometeam_id', dependent: :destroy
	has_many :awayteams, :class_name => "Game", :foreign_key => 'awayteam_id', dependent: :destroy
	has_many :winningteams, :class_name => "Game", :foreign_key => 'winningteam_id', dependent: :destroy

  validates :yearfounded, numericality: { only_integer: true, greater_than: 0, less_than: 2020 }

   def full_name
  	"#{fullname}"
  end
  
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article, :foreign_key => 'email'
  # belongs_to :user
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :only => [:new, :create, :edit, :update, :destroy] do
    if (! (current_app_user && current_app_user.admin) )
      flash[:alert] = 'Only admins can access that functionality.' 
      redirect_to(root_path)
    end
  end
  before_action :set_player, only: [:show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    @players = Player.all
  end

  # GET /players/1
  # GET /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to @player, notice: 'Player was successfully created.' }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, notice: 'Player was successfully updated.' }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Player was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:firstname, :lastname, :nationality, :position, :yearsofexperience, :salary, :team_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/players/_form.html.erb
<%= form_with(model: @player, url: @player.new_record? ? team_players_path : player, local: true) do |form| %>
  <% if player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
      <% player.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :firstname %>
    <%= form.text_field :firstname %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname %>
  </div>

  <div class="field">
    <%= form.label :nationality %>
    <%= form.text_field :nationality %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :yearsofexperience %>
    <%= form.number_field :yearsofexperience %>
  </div>

  <div class="field">
    <%= form.label :salary %>
    <%= form.number_field :salary %>
  </div>

  <div class="select">
    <%= form.label :team_id %>
    <% form.text_field :team_id %>
    <%= form.collection_select(:team_id, Team.all, :id, :full_name) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing Player</h1>

<%= render 'form', player: @player %>
<br>
<%= link_to 'Show', @player, class: 'btn btn-primary' %> |
<%= link_to 'Back to Players', team_players_path(@player.team), class: 'btn btn-primary' %>

app/views/players/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Players</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>First Name </th>
      <th>Last Name </th>
      <th>Nationality </th>
      <th>Position </th>
      <th>Years Experience </th>
      <th>Salary </th>
      <th>Team </th>
      <th scope="col">Links</th>
      <th scope="col" colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @players.each do |player| %>
      <% if player.team_id == params{1}["team_id"].to_i %>
      <tr>
        <td><%= player.firstname %></td>
        <td><%= player.lastname %></td>
        <td><%= player.nationality %></td>
        <td><%= player.position %></td>
        <td><%= player.yearsofexperience %></td>
        <td><span class="input-group-addon">$</span><%= number_with_delimiter(player.salary, :delimiter => ',') %></td>
        <td><%= player.team.fullname %></td>
        <td><%= link_to ("<i class='far fa-eye'></i>").html_safe, player_path(player) %></td>
        <td><%= link_to ("<i class='fas fa-edit fa-sm'></i>").html_safe, edit_player_path(player) %></td> 
        <td><%= link_to ("<i class='fa fa-trash fa-sm'></i>").html_safe, player, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Player', new_team_player_path, class: 'btn btn-primary' %>

app/views/players/new.html.erb
<h1>New Player</h1>

<%= render 'form', player: @player %>

<%= link_to 'Back', team_players_path, class: 'btn btn-primary' %>

app/views/players/show.html.erb
<p>
  <strong>First Name:</strong>
  <%= @player.firstname %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @player.lastname %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @player.nationality %>
</p>

<p>
  <strong>Position:</strong>
  <%= @player.position %>
</p>

<p>
  <strong>Years Experience:</strong>
  <%= @player.yearsofexperience %>
</p>

<p>
  <strong>Salary:</strong>
  <span class="input-group-addon">$</span>
  <%= number_with_delimiter(@player.salary, :delimiter => ',') %>
</p>

<strong>Team:</strong>
  <%= @player.team.fullname %>
</p>

<%= link_to 'Edit', edit_player_path(@player), class: 'btn btn-primary' %> 
<%= link_to 'Back', team_players_path(@player.team), class: 'btn btn-primary' %>