config/routes.rb
Rails.application.routes.draw do
  mount ReportsKit::Engine, at: '/'

  get 'query/search' => 'query#search', :as => 'search_page'
  get 'query' => 'query#index'
  post 'query/search' => 'query#search'
  post 'query/game' => 'query#game'

  devise_for :app_users
  resources :votes
  resources :games
  resources :teams, shallow: true do
  	resources :players 
  	resources :coaches 
  	resources :owners  
  	resources :managers 
    resources :articles do
      resources :comments, only: [:create, :index, :destroy]
    end
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'teams#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/app_user.rb
class AppUser < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

 	has_many :comments, dependent: :destroy

end

app/models/article.rb
class Article < ApplicationRecord
  # self.primary_keys = :title, :team_id
  belongs_to :team
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :title, presence: true, allow_blank: false
  validates :articletext, presence: true, allow_blank: false
end

app/models/coach.rb
class Coach < ApplicationRecord
  belongs_to :team
end

app/models/comment.rb
class Comment < ApplicationRecord
  # belongs_to :article, :foreign_key => [:title, :team_id]
  belongs_to :article
  belongs_to :app_user


  validates :body, presence: true, allow_blank: false
end

app/models/game.rb
class Game < ApplicationRecord
	self.primary_keys = :hometeam_id, :gamedate
  belongs_to :hometeam, :class_name => 'Team'
  belongs_to :awayteam, :class_name => 'Team'
  belongs_to :winningteam, :class_name => 'Team', optional: true

end

app/models/manager.rb
class Manager < ApplicationRecord
  belongs_to :team
end

app/models/owner.rb
class Owner < ApplicationRecord
  belongs_to :team
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
	has_many :players, dependent: :destroy
	has_many :managers, dependent: :destroy
	has_one :owner, dependent: :destroy
	has_many :coaches, dependent: :destroy
	has_many :articles, dependent: :destroy

	has_many :hometeams, :class_name => "Game", :foreign_key => 'hometeam_id', dependent: :destroy
	has_many :awayteams, :class_name => "Game", :foreign_key => 'awayteam_id', dependent: :destroy
	has_many :winningteams, :class_name => "Game", :foreign_key => 'winningteam_id', dependent: :destroy

  validates :yearfounded, numericality: { only_integer: true, greater_than: 0, less_than: 2020 }

   def full_name
  	"#{fullname}"
  end
  
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article, :foreign_key => 'email'
  # belongs_to :user
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/coaches_helper.rb
module CoachesHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/query_helper.rb
module QueryHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Premier League Fan Site</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="/"><i class="fas fa-futbol"></i></a>
    <p> </p>
    <a class="navbar-brand" href="/">Premier League Fan Site</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">Teams <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/games">Games</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/query/">Queries</a>
        </li>
        <%= form_tag(search_page_path, :method => "get",   
        class: 'navbar-form navbar-left') do %>  
        <div class="input-group">  
          <%= search_field_tag :search, params[:search], placeholder: "Insert SQL query", class: "form-control" %>  
          <div class="input-group-btn">  
             <%= submit_tag "Execute", class: 'btn btn-primary' %>  
          </div>  
        </div>  
      <% end %>
        <% if app_user_signed_in? %>
        <li class="nav-item">
          <a class="nav-link">Logged in as
          <strong><%= current_app_user.email %></strong></a>
        </li>
        <li class="nav-item">   
            <%= link_to 'Profile', edit_app_user_registration_path, class: "nav-link" %> 
        </li>
        <li class="nav-item"> 
            <%= link_to "Logout", destroy_app_user_session_path, method: :delete, class: "nav-link" %>
        </li>
            <% else %>
        <li class="nav-item"> 
            <%= link_to "Sign up", new_app_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item"> 
            <%= link_to "Login", new_app_user_session_path, class: "nav-link"  %>
        </li>
        <% end %>
        </li>
      </ul>
<!--       <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Query (not working yet)" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" href="/" type="submit">Search</button>
      </form> -->
    </div>
  </nav>
    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-3">
        </div>
        <div class="col-xs-9">
          <p class="navbar-text pull-right">
          <% if notice %>
          <p class="alert alert-success"><%= notice %></p>
          <% end %>
          <% if alert %>
          <p class="alert alert-danger"><%= alert %></p>
          <% end %>
          <%= yield %>
        </div>
      </div>
    </div>
  <footer>
  <div class="container">
    <!-- CPSC 304 <%= Time.now.year %> -->
  </div>
  </footer>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
</html>